### ISSUE TITLE
[Bug]: Too many duplicate reports when repo is in idl.IDL.path and in workspace

### ISSUE THREAD

**Issue by martinwiesmann** [interactive-data-language/vscode-idl#49]
### Current Behavior

If I open a repository in my Workspace so that I can edit the files, I get 'duplicate' warnings for all methods, procedures and functions if the repository is also added to the setting idl.IDL.path. When I close or change the workspace this duplicate warnings disappear.

I think that this bug only appears when the directory of the repo is on another disk than VScode. Or even only when it is on another machine, as is the case on my system.

### Expected Behavior

I would expect the editor to realise that the files in the workspace are the same ones as the one given in idl.IDL.path and thus not issue warning about duplicates.

### Steps to Reproduce

1. Create a directory on another machine, which the current machine has access to.
2. Create a pro file with a procedure and/or function.
3.  Check the warnings when the directory is in the workspace and when it is not.

### Operating System

- [X] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [X] Linux
- [ ] Windows

### IDL Version

9.1.0

**Comment by znorman-harris** [comment]
I just did a quick sanity check on this one and was not able to reproduce it. We also [explicitly](https://github.com/interactive-data-language/vscode-idl/blob/827448db5c14dc54445f9eb0f3754d5b5fb8c594/libs/parsing/index/src/lib/idl-index.class.ts#L1281) added logic to our file discovery that will not track duplicate files using the `Set` class/object for typescript/javascript to handle exactly these cases.

My steps:

1. Add the "scratch" folder from the extension source code to IDL's path in VSCode (middle of the screenshot below)
2. Open the "scratch" folder as a workspace (name in left sidebar of image below)
3. Properly see that there are no duplicate routines present in the workspace in the PRO file on the right (screenshot below)

Are you using symbolic links anywhere or are there other duplicate files present? Maybe we can tweak the error message that gets reported to try and identify the other files where duplicates are present to help track down what is going on here.

The `Set` object class will not exclude files if they have different paths altogether. So that makes me think that you have something with symbolic links where there are multiple "paths" to the same file on disk.

---

Screenshot of my workspace:

![image](https://github.com/user-attachments/assets/fa701f6d-5925-4eb1-a96a-a23e10bc07bf)

**Comment by martinwiesmann** [comment]
Yes you are right, there is a symbolic link in our system, which I wasn't aware of. If I use the actual, physical path to the repository, I do not get all these duplicate warnings. 
So, this bug report can be closed.
Thanks for the quick replies.

**Comment by znorman-harris** [comment]
OK, thanks for the confirmation! I will add, if you run into this again, we can probably add an option for file discovery to not follow symbolic links.

I'll bring this up with the team today and see what their thoughts are on this before closing.

**Comment by steinhh** [comment]
Hi @znorman-harris! 

Martin's colleague here: the problem was not following links *from* the workspace to somewhere, it was the fact that the workspace was accessed through and referred to via symlinks.

As in: 

* The workspace was opened in VSCode as "/storage/martin/ws"
* The idl.IDL.path value was also set to "/storage/martin/ws"
* But /storage was a symlink to /mn/filesys
* So the physical path was "/mn/filesys/martin/ws"
* When we changed the idl.IDL.path value to the physical path, the problem went away

So one fix would be to resolve all paths to their physical paths before using the Set trick, that would also work for symlinks out of the workspace. However, you might need some additional bookkeeping in order to report errors/warnings using the symlinked path, which is presumably the user's preference.

**Comment by znorman-harris** [comment]
Just published a new version of the extension which should fix this issue. If it doesn't, let me know and I can try to get an environment set up for testing!

**Comment by znorman-harris** [comment]
Just a heads up, I just published a new release of the extension with our improved support for symbolic links. There were some cascading changes that I needed to sort through, so apologies it took a couple of weeks to get this wrapped up.

Let me know if the latest version doesn't fix your issues and I can take a look again!

**Comment by martinwiesmann** [comment]
I just realised that the latest version doesn't fix all problems with symbolic links. I think this is a problem that already existed before, but I am not entirely sure:

If I open a symbolic link in the workspace, e.g. in the terminal:
` code /path/link_to_repository`

then problems are reported in the 'Problems' window, but the filenames are not coloured if there is a problem within, nor are the problems shown when I open the file. Only if I click on one of the problems in the 'Problems' window, the errors are shown in the editor. I guess, because the file is opened with the physical path.
